### PR TITLE
Merging Devise branch to development

### PR DESCRIPTION
**Pull request by rsundar**
# FEATURES IMPLEMENTED

These are the features which were implemented for this project.

- We created a posts and user model (with devise).
- We created associations between post and user models.
- We allow only the owner of a post to edit or delete the post.
- We provided a user sign-up page, as well as a user login page.
- We display the user name of the anonymous post depending on whether the user is logged in or not.

Kindly review our code and contact us over slack (@rsundar or @MarioBS) for any clarifications or request for changes. 

Thanks

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work! @rsundar and @mariobarrioss! :rocket: 
You have done such a wonderful job building this. Please look to my comment below, make the required change, and request another review! I wish you the very best and see you at the top :rocket: 

#### Before action helper in Application Controller
It uses before_action to restrict access to the :new and :create methods (uses ApplicationController helper method)
screenshot
##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by rsundar** [comment]
# CHANGES MADE

We made the following changes as requested by the reviewer @Oluwadamilareolusakin 

- Creating a new post now requires the user to sign in or sign up.

**Review by wathigo — APPROVED** [review]
### Approved :heavy_check_mark: 
Great work team :clap: 
The suggested change have been implemented.

**You may proceed to the next project.**

**All the best  :four_leaf_clover: 
Simon Wathigo**

**Comment by rsundar** [comment]
Thank you @Oluwadamilareolusakin @wathigo , your help was greatly appreciated.

**Pull request merged**
